KEYS_NAMES:
  - "alpha"
  - "hash"
  - "k-mer"
  - "relaxed-fpr"
  - "no U no R"
  - "U"
  - "U and R"

PLOT_TIME_FORMAT:
  - "SUBKEY"
  - "compute_minimiser_avg_in_seconds"
  - "query_ibf_avg_in_seconds"
  - "generate_results_avg_in_seconds"
  - "wall_clock_time_in_seconds"
  - "determine_query_length_in_seconds"
  - "query_file_io_in_seconds"
  - "load_index_in_seconds"
  - "compute_minimiser_max_in_seconds"
  - "query_ibf_max_in_seconds"
  - "generate_results_max_in_seconds"

# How many entries in PLOT_TIME_FORMAT after "SUBKEY" are advanced
PLOT_TIME_ADVANCED_OFFSET: 4

TIME_NAMES:
  - "Compute minimizer (avg)"
  - "Query IBF (avg)"
  - "Generate results (avg)"
  - "Wall clock time"
  - "Determine query length"
  - "Queryfile IO"
  - "Load index"
  - "Compute minimizer (max)"
  - "Query IBF (max)"
  - "Generate results (max)"

PLOT_SIZE_FORMAT:
  - "SUBKEY"
  - "LEVEL_0"
  - "LEVEL_1"
  - "LEVEL_2"
  - "LEVEL_3"

SIZE_NAMES:
  - "Level 0"
  - "Level 1"
  - "Level 2"
  - "Level 3"
