name: Delete Preview

on:
  pull_request_target:
    types:
      - closed

concurrency:
  group: delete-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

jobs:
  delete_preview:
    name: Delete Preview
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan'
    timeout-minutes: 30
    steps:
    - name: Delete Preview
      uses: seqan/actions/documentation_delete_preview@main
      with:
        deploy_host: ${{ secrets.DEPLOY_HOST }}
        deploy_user: ${{ secrets.DEPLOY_USER }}
        deploy_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
        deploy_base_path: ${{ secrets.DEPLOY_PREVIEW_BASE_PATH }}
