name: Lint

on:
  pull_request_target:

concurrency:
  group: lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -el {0}

jobs:
  auto-lint:
    name: Formatting
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    outputs:
      has_changes: ${{ steps.commit.outputs.committed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}

      - name: Cache conda
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          save-always: true
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: snakemake
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: Run isort
        run: isort .

      - name: Run black
        run: black .

      - name: Run snakefmt
        run: snakefmt .

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: seqan-actions[bot]
          author_email: seqan-actions@users.noreply.github.com
          message: '[MISC] automatic linting'

  lint:
    needs: auto-lint
    if: needs.auto-lint.outputs.has_changes == 'false'
    name: Style Guide
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          save-always: true
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: snakemake
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: Run pylint
        run: pylint .

