name: Test

on:
  pull_request_target:

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -el {0}

jobs:
  build-html:
    name: Build HTML
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan'
    timeout-minutes: 30
    steps:
      # pull_request_target does not checkout the merge commit by default
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: snakemake
          auto-activate-base: false
          auto-update-conda: false
          channels: conda-forge
          channel-priority: strict
          environment-file: workflow/envs/snakemake.yml
          miniforge-version: latest
          use-mamba: true

      - name: Extract data
        run: |
          mkdir -p ${{ github.workspace }}/results/raw_data
          tar xf ${{ github.workspace }}/.github/data/data.tar.zst -C ${{ github.workspace }}/results/raw_data

      - name: Run snakemake
        run: snakemake --use-conda --cores $(nproc)

      - name: Deploy Preview
        if: github.repository_owner == 'seqan'
        uses: seqan/actions/documentation_deploy_preview@main
        with:
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          deploy_base_path: ${{ secrets.DEPLOY_PREVIEW_BASE_PATH }}
          source_path_user_doc: results/html
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
