name: Test

on:
  pull_request:

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -el {0}

jobs:
  build-html:
    name: build
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          save-always: true
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: snakemake
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: Build HTML
        run:  python3 scripts/main.py
